### ISSUE TITLE
Display user location

### ISSUE THREAD

**Issue by ayulockin** [thecodefoundation/Vison-WoC-Frontend#7]
This will show the current location of the user. Just the state and country is required. If possible it should be done on the client side itself.

![location](https://user-images.githubusercontent.com/31141479/66479105-6a9c7a80-eab9-11e9-9b6f-40635f353976.png)

**Comment by dotslash21** [comment]
Hi! I would like to work on this issue.

**Comment by ayulockin** [comment]
Sure go ahead. :) @dotslash21
